import { useEffect, useMemo, useState } from 'react';
import InfoTooltip from '../components/coingame/InfoTooltip';
import { useFinanceStore } from '../store/useFinanceStore';

function FC({ amount, decimals = 2 }) {
  return (
    <span>
      {Number(amount ?? 0).toLocaleString(undefined, { maximumFractionDigits: decimals })}
      <span style={{ marginLeft: '0.25em', fontSize: '0.75em', color: 'var(--cg-text-3)', fontFamily: 'var(--cg-font-mono)' }}>FC</span>
    </span>
  );
}

function BetHistory({ bets }) {
  return (
    <div className="cg-table">
      <div className="cg-table-header">
        <span className="cg-table-title">
          Recent Bets
          <InfoTooltip text="Your recent casino bets. Results are generated by backend RPCs and settled instantly in FC." />
        </span>
        <span style={{ fontSize: '0.78rem', color: 'var(--cg-text-3)', fontFamily: 'var(--cg-font-mono)' }}>
          {bets.length} records
        </span>
      </div>
      {bets.length === 0 ? (
        <div className="cg-empty">
          <div className="cg-empty-icon">$</div>
          <div className="cg-empty-title">No bets yet</div>
          <div className="cg-empty-desc">Play coinflip or dice to start the log</div>
        </div>
      ) : (
        bets.map((bet) => (
          <div className="cg-row" key={bet.id}>
            <div className={`cg-casino-result-dot ${bet.result}`}>
              {bet.result === 'win' ? '+' : '-'}
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontWeight: 700, fontSize: '0.875rem' }}>
                {bet.game === 'coinflip' ? 'Coinflip' : 'Dice'}
                <span style={{ color: 'var(--cg-text-3)', fontWeight: 400, marginLeft: '0.4rem' }}>
                  {bet.game === 'coinflip' ? bet.choice : `target ${bet.target}`}
                </span>
              </div>
              <div style={{ fontSize: '0.74rem', color: 'var(--cg-text-3)', fontFamily: 'var(--cg-font-mono)' }}>
                Roll {bet.roll} - {Number(bet.multiplier ?? 0).toFixed(4)}x
              </div>
            </div>
            <div style={{ textAlign: 'right', fontFamily: 'var(--cg-font-mono)', color: bet.result === 'win' ? 'var(--cg-positive)' : 'var(--cg-danger)' }}>
              {Number(bet.net_fc) >= 0 ? '+' : ''}<FC amount={bet.net_fc} />
              <div style={{ color: 'var(--cg-text-3)', fontSize: '0.72rem' }}>
                wager <FC amount={bet.wager_fc} />
              </div>
            </div>
          </div>
        ))
      )}
    </div>
  );
}

function ResultPanel({ result }) {
  if (!result) return null;
  const won = result.result === 'win';
  return (
    <div className={`cg-casino-result ${won ? 'win' : 'loss'}`}>
      <div>
        <span>{won ? 'WIN' : 'LOSS'}</span>
        <strong>{result.game === 'coinflip' ? String(result.roll).toUpperCase() : `ROLL ${result.roll}`}</strong>
      </div>
      <div>
        <span>Net</span>
        <strong>{Number(result.net_fc) >= 0 ? '+' : ''}<FC amount={result.net_fc} /></strong>
      </div>
      <div>
        <span>Payout</span>
        <strong><FC amount={result.payout_fc} /></strong>
      </div>
    </div>
  );
}

function CoinflipCard({ wager, setWager, onPlay, busy }) {
  const [choice, setChoice] = useState('heads');
  const payout = Number(wager || 0) * 1.96;

  return (
    <section className="cg-casino-card">
      <div className="cg-casino-card-head">
        <div>
          <span>GAME 01</span>
          <h2>Coinflip</h2>
        </div>
        <InfoTooltip text="Choose heads or tails. A win pays 1.96x total payout with 2% house edge." />
      </div>

      <div className="cg-casino-choice-grid">
        {['heads', 'tails'].map((item) => (
          <button key={item} className={choice === item ? 'active' : ''} onClick={() => setChoice(item)}>
            {item.toUpperCase()}
          </button>
        ))}
      </div>

      <label className="cg-label">Wager</label>
      <input className="cg-input" value={wager} onChange={(event) => setWager(event.target.value)} inputMode="decimal" />

      <div className="cg-casino-preview">
        <div><span>Multiplier</span><strong>1.9600x</strong></div>
        <div><span>Win payout</span><strong><FC amount={payout} /></strong></div>
      </div>

      <button className="cg-btn cg-btn-primary cg-casino-play" disabled={busy} onClick={() => onPlay(choice)}>
        {busy ? 'Rolling...' : 'Flip Coin'}
      </button>
    </section>
  );
}

function DiceCard({ wager, setWager, onPlay, busy }) {
  const [target, setTarget] = useState(50);
  const multiplier = useMemo(() => (100 / Number(target || 1)) * 0.98, [target]);
  const payout = Number(wager || 0) * multiplier;

  return (
    <section className="cg-casino-card">
      <div className="cg-casino-card-head">
        <div>
          <span>GAME 02</span>
          <h2>Dice Target</h2>
        </div>
        <InfoTooltip text="Pick a target from 1 to 95. You win when the backend roll is less than or equal to your target." />
      </div>

      <label className="cg-label">Target 1-95</label>
      <input
        className="cg-input"
        type="number"
        min="1"
        max="95"
        value={target}
        onChange={(event) => setTarget(event.target.value)}
      />
      <input
        className="cg-casino-slider"
        type="range"
        min="1"
        max="95"
        value={target}
        onChange={(event) => setTarget(event.target.value)}
      />

      <label className="cg-label">Wager</label>
      <input className="cg-input" value={wager} onChange={(event) => setWager(event.target.value)} inputMode="decimal" />

      <div className="cg-casino-preview">
        <div><span>Win chance</span><strong>{Number(target || 0)}%</strong></div>
        <div><span>Multiplier</span><strong>{multiplier.toFixed(4)}x</strong></div>
        <div><span>Win payout</span><strong><FC amount={payout} /></strong></div>
      </div>

      <button className="cg-btn cg-btn-primary cg-casino-play" disabled={busy} onClick={() => onPlay(Number(target))}>
        {busy ? 'Rolling...' : 'Roll Dice'}
      </button>
    </section>
  );
}

export default function CoingameCasinoPage() {
  const wallet = useFinanceStore((s) => s.coingameWallet);
  const casino = useFinanceStore((s) => s.coingameCasino);
  const bets = useFinanceStore((s) => s.coingameGamblingBets);
  const status = useFinanceStore((s) => s.coingameStatus);
  const storeError = useFinanceStore((s) => s.coingameError);
  const lastResult = useFinanceStore((s) => s.coingameLastGambleResult);
  const loadCasino = useFinanceStore((s) => s.loadCoingameCasino);
  const playCoinflip = useFinanceStore((s) => s.coingameGambleCoinflip);
  const playDice = useFinanceStore((s) => s.coingameGambleDice);
  const [wager, setWager] = useState('100');
  const [error, setError] = useState('');

  useEffect(() => { loadCasino(); }, [loadCasino]);

  const busy = status === 'loading';

  async function run(fn) {
    const numericWager = Number(wager);
    if (!Number.isFinite(numericWager) || numericWager <= 0) {
      setError('Enter a positive wager.');
      return;
    }
    setError('');
    try {
      await fn(numericWager);
    } catch (err) {
      setError(err.message || 'Bet failed');
    }
  }

  return (
    <div className="cg-page cg-casino-page">
      <div className="cg-page-header">
        <div>
          <div className="cg-kicker">FC ONLY</div>
          <h1>Casino</h1>
          <p>Coinflip and dice settle instantly against the Coingame house pool.</p>
        </div>
      </div>

      <div className="cg-casino-stats">
        <div className="cg-stat-card">
          <div className="cg-stat-label">Wallet</div>
          <div className="cg-stat-value accent"><FC amount={wallet?.fc_balance} /></div>
        </div>
        <div className="cg-stat-card">
          <div className="cg-stat-label">House Pool</div>
          <div className="cg-stat-value"><FC amount={casino?.house_balance_fc} /></div>
        </div>
        <div className="cg-stat-card">
          <div className="cg-stat-label">House Edge</div>
          <div className="cg-stat-value">{(Number(casino?.house_edge ?? 0.02) * 100).toFixed(2)}%</div>
        </div>
      </div>

      {(error || storeError) && <div className="cg-error">{error || storeError}</div>}
      <ResultPanel result={lastResult} />

      <div className="cg-casino-grid">
        <CoinflipCard wager={wager} setWager={setWager} onPlay={(choice) => run((amount) => playCoinflip(choice, amount))} busy={busy} />
        <DiceCard wager={wager} setWager={setWager} onPlay={(target) => run((amount) => playDice(target, amount))} busy={busy} />
      </div>

      <BetHistory bets={bets} />
    </div>
  );
}
